window.Modernizr=(function(window,document,undefined){var version='2.8.3',Modernizr={}.toString,body=document.body,fakeBody=body||document.createElement('body');if(parseInt(nodes,10)){while(nodes--){node=document.createElement('div');node.id=testnames?testnames[nodes]:mod+(nodes+1);div.appendChild(node)}}
    if(!body){fakeBody.parentNode.removeChild(fakeBody);docElement.style.overflow=docOverflow}else{div.parentNode.removeChild(div)}
    return!!ret},testMediaQuery=function(mq){var matchMedia=window.matchMedia||window.msMatchMedia;if(matchMedia){return matchMedia(mq)&&matchMedia(mq).matches||!1}
        var bool;injectElementWithStyles('@media '+mq+'{#'+mod+'{position:absolute}}',function(node){bool=(window.getComputedStyle?getComputedStyle(node,null):node.currentStyle)['position']=='absolute'});return bool},isEventSupported=(function(){var TAGNAMES={'select':'input','change':'input','submit':'form','reset':'form','error':'img','load':'img','abort':'img'};function isEventSupported(eventName,element){element=element||document.createElement(TAGNAMES[eventName]||'div');eventName='on'+eventName;var isSupported=eventName in element;if(!isSupported){_hasOwnProperty=({}).hasOwnProperty,hasOwnProp;if(!is(_hasOwnProperty,'undefined')&&!is(_hasOwnProperty.call,'undefined')){hasOwnProp=function(object,property){return _hasOwnProperty.call(object,property)}}
        else{hasOwnProp=function(object,property){return((property in object)&&is(object.constructor.prototype[property],'undefined'))}}
            function testProps(props,prefixed){for(var i in props){var prop=props[i];if(!contains(prop,"-")&&mStyle[prop]!==undefined){return prefixed=='pfx'?prop:!0}}
                return!1}
            function testDOMProps(props,obj,elem){for(var i in props){var item=obj[props[i]];if(item!==undefined){if(is(item,'function')){return item.bind(elem||obj)}
                return item}}
                return!1}
            function testPropsAll(prop,prefixed,elem){var ucProp=prop.charAt(0).toUpperCase()+prop.slice(1),props=(prop+' '+cssomPrefixes.join(ucProp+' ')+ucProp).split(' ');if(is(prefixed,"string")||is(prefixed,"undefined")){return testProps(props,prefixed)}else{props=(prop+' '+(domPrefixes).join(ucProp+' ')+ucProp).split(' ');return testDOMProps(props,prefixed,elem)}}
            tests.flexbox=function(){return testPropsAll('flexWrap')};tests.flexboxlegacy=function(){return testPropsAll('boxDirection')};tests.canvas=function(){var elem=document.createElement('canvas');return!!(elem.getContext&&elem.getContext('2d'))};tests.canvastext=function(){return!!(Modernizr.canvas&&is(document.createElement('canvas').getContext('2d').fillText,'function'))};tests.webgl=function(){return!!window.WebGLRenderingContext};tests.touch=function(){var bool;if(('ontouchstart' in window)||window.DocumentTouch&&document instanceof DocumentTouch){bool=!0}else{injectElementWithStyles(['@media (',prefixes.join('touch-enabled),('),mod,')','{#modernizr{top:9px;position:absolute}}'].join(''),function(node){bool=node.offsetTop===9})}
                return bool};tests.geolocation=function(){return 'geolocation' in navigator};tests.postmessage=function(){return!!window.postMessage};tests.websockets=function(){return 'WebSocket' in window||'MozWebSocket' in window};tests.rgba=function(){setCss('background-color:rgba(150,255,150,.5)');return contains(mStyle.backgroundColor,'rgba')};tests.hsla=function(){setCss('background-color:hsla(120,40%,100%,.5)');return contains(mStyle.backgroundColor,'rgba')||contains(mStyle.backgroundColor,'hsla')};tests.multiplebgs=function(){setCss('background:url(https://),url(https://),red url(https://)');return(/(url\s*\(.*?){3}/).test(mStyle.background)};tests.backgroundsize=function(){return testPropsAll('backgroundSize')};tests.borderimage=function(){return testPropsAll('borderImage')};tests.borderradius=function(){return testPropsAll('borderRadius')};tests.boxshadow=function(){return testPropsAll('boxShadow')};tests.textshadow=function(){return document.createElement('div').style.textShadow===''};tests.opacity=function(){setCssAll('opacity:.55');return(/^0.55$/).test(mStyle.opacity)};tests.cssanimations=function(){return testPropsAll('animationName')};tests.csscolumns=function(){return testPropsAll('columnCount')};tests.cssgradients=function(){var str1='background-image:',str2='gradient(linear,left top,right bottom,from(#9f9),to(white));',str3='linear-gradient(left top,#9f9,white);';setCss((str1+'-webkit-'.split(' ').join(str2+str1)+prefixes.join(str3+str1)).slice(0,-str1.length));return contains(mStyle.backgroundImage,'gradient')};tests.cssreflections=function(){return testPropsAll('boxReflect')};tests.csstransforms=function(){return!!testPropsAll('transform')};tests.csstransforms3d=function(){var ret=!!testPropsAll('perspective');if(ret&&'webkitPerspective' in docElement.style){injectElementWithStyles('@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px}}',function(node,rule){ret=node.offsetLeft===9&&node.offsetHeight===3})}
                    return ret};tests.csstransitions=function(){return testPropsAll('transition')};tests.fontface=function(){var bool;injectElementWithStyles('@font-face{font-family:"font";src:url("https://")}',function(node,rule){var style=document.getElementById('smodernizr'),sheet=style.sheet||style.styleSheet,cssText=sheet?(sheet.cssRules&&sheet.cssRules[0]?sheet.cssRules[0].cssText:sheet.cssText||''):'';bool=/src/i.test(cssText)&&cssText.indexOf(rule.split(' ')[0])===0});return bool};tests.generatedcontent=function(){var bool;injectElementWithStyles(['#',mod,'{font:0/0 a}#',mod,':after{content:"',smile,'";visibility:hidden;font:3px/1 a}'].join(''),function(node){bool=node.offsetHeight>=3});return bool};Modernizr.input=(function(props){for(var i=0,len=props.length;i<len;i++){attrs[props[i]]=!!(props[i]in inputElem)}
                        if(attrs.list){if(bool){inputElem.value=smile;inputElem.style.cssText='position:absolute;visibility:hidden;';if(/^range$/.test(inputElemType)&&inputElem.style.WebkitAppearance!==undefined){docElement.appendChild(inputElem);defaultView=document.defaultView;bool=defaultView.getComputedStyle&&defaultView.getComputedStyle(inputElem,null).WebkitAppearance!=='textfield'&&(inputElem.offsetHeight!==0);docElement.removeChild(inputElem)}else if(/^(search|tel)$/.test(inputElemType)){}else if(/^(url|email)$/.test(inputElemType)){bool=inputElem.checkValidity&&inputElem.checkValidity()===!1}else{bool=inputElem.value!=smile}}
                            inputs[props[i]]=!!bool}
                        return inputs})('search tel url email datetime date month week time datetime-local number range color'.split(' '))}
            for(var feature in tests){if(hasOwnProp(tests,feature)){Modernizr.prefixed=function(prop,obj,elem){if(!obj){return testPropsAll(prop,'pfx')}else{return testPropsAll(prop,obj,elem)}};docElement.className=docElement.className.replace(/(^|\s)no-js(\s|$)/,'$1$2')+(enableClasses?' js '+classes.join(' '):'');return Modernizr})(this,this.document)