$(function(){initializeTablePrioritySetting();intializeTableCRUD();if($(this).scrollTop()==0){$('#exportBtn').fadeIn()}});function initializeTablePrioritySetting(){initializeTableSorting();initializeUpDownSorting()}
function intializeTableCRUD(){delete_row();add_row()}
function initializeUpDownSorting(){$(document).on('click','.moveuplink',function(){$(this).parents(".sectionsid").insertBefore($(this).parents(".sectionsid").prev());renumber_table('#diagnosis_list')});$(document).on('click','.movedownlink',function(){$(this).parents(".sectionsid").insertAfter($(this).parents(".sectionsid").next());renumber_table('#diagnosis_list')})}
function initializeTableSorting(){var fixHelperModified=function(e,tr){var $originals=tr.children();var $helper=tr.clone();$helper.children().each(function(index){$(this).width($originals.eq(index).width())});return $helper};$("#diagnosis_list tbody").sortable({helper:fixHelperModified,stop:function(event,ui){renumber_table('#diagnosis_list')}}).disableSelection()}
function renumber_table(tableID){$(tableID+" tr").each(function(){count=$(this).parent().children().index($(this))+1;$(this).find('.priority').html(count)})}
function add_row(){$("#addBtn").on("click",function(){var highestIDvalue=retrieve_HighestID();var incrementid=parseInt(highestIDvalue)+1;var tableRowIdNaming="sectionsid_";var rowID=tableRowIdNaming.concat(incrementid);var selectedDDLValueNaming="selectoptionid_"
var dropdownID=selectedDDLValueNaming.concat(incrementid);var inputMinValueNaming="inputMinID_"
var inputMinID=inputMinValueNaming.concat(incrementid);var inputMaxValueNaming="inputMaxID_"
var inputMaxID=inputMaxValueNaming.concat(incrementid);var firstinputIdNaming="min_";var secondinputIdNaming="max_";var minID=firstinputIdNaming.concat(incrementid);var maxID=secondinputIdNaming.concat(incrementid);var newRowTest=""+"<tr class='sectionsid' id='"+rowID+"'> "+"<td class='priority col-sm-1'>"+incrementid+"</td>"+"<td class='col-sm-1'>"+"   <a href='javascript:void(0)' class='moveuplink'>"+"       <i class='glyphicon glyphicon-arrow-up'></i>"+"   </a>"+"   <a href='javascript:void(0)' class='movedownlink'>"+"       <i class='glyphicon glyphicon-arrow-down'></i>"+"   </a>"+"</td>"+"<td class='col-sm-3'>"+"   <select class='form-control' name='"+dropdownID+"' id='exampleSelect1'>"+"       <option value='CIPlanned' >Crane Intensity</option>"+"       <option value='Ballast' >Ballast(mt)</option>"+"       <option value='TotalMoves' >Move Count</option>"+"   </select>"+"</td>"+"<td>"+"   <input type='number' class='form-control' value='0' min='0'  name='"+inputMinID+"' id='"+minID+"' step='any'"+"       onblur='stripNonNumeric(this)' onkeyup='validateTextBoxes(this);' onkeypress='return isNumber(event)'>"+"</td>"+"<td>"+"   <input type='number' class='form-control' value='0' min='0' name='"+inputMaxID+"'  id='"+maxID+"' step='any'"+"       onblur='stripNonNumeric(this)' onkeyup='validateTextBoxes(this);' onkeypress='return isNumber(event)'>"+"</td>"+"<td class='col-sm-1'>"+"   <a class='btn btn-delete btn-danger btn-block'><span class='glyphicon glyphicon-trash'></span></a>"+"</td>"+"</tr>";$("#diagnosis_list").append(newRowTest);renumber_table('#diagnosis_list')})}
function delete_row(){$('table').on('click','.btn-delete',function(){tableID='#'+$(this).closest('table').attr('id');r=confirm('Delete this item?');if(r){$(this).closest('tr').remove()}
renumber_table('#diagnosis_list')})}
function retrieve_HighestID(){var max=0;$(".sectionsid").each(function(){num=parseInt(this.id.split("_")[1],10);if(num>max){max=num}});return max}